name: GEE Data Workflow

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight
  workflow_dispatch:  # Manual trigger

jobs:
  fetch-gee-data:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          
      - name: Install R packages
        run: |
          install.packages(c("rgee", "reticulate"))
        shell: Rscript {0}
         
      - name: Install rgee dependancies
        run: |
          Rscript -e "
            library(rgee)
            ee_install(py_env = 'rgee', confirm = FALSE)
            "
          
      - name: Run GEE script
        env:
          GEE_SERVICE_ACCOUNT: ${{ secrets.GEE_SERVICE_ACCOUNT }}
          GEE_PRIVATE_KEY: ${{ secrets.EARTH_ENGINE_KEY }}
        run: |
             echo "$GEE_PRIVATE_KEY" > private-key.json
             Rscript get_data.R
